# Generated by Django 2.2.12 on 2020-05-27 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='measurement_units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('unit_qty', models.PositiveIntegerField(default=0.0, verbose_name='Factor de Medida')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abbreviación')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'measurement_units',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='product_units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Cantidad')),
                ('pieces', models.PositiveIntegerField(default=0.0, verbose_name='Piezas')),
                ('measure', models.CharField(max_length=30, verbose_name='Medida')),
                ('stock_ctrl', models.BooleanField(default=False)),
                ('fixed_ammount', models.BooleanField(default=False, verbose_name='Fijar Cantidad')),
                ('first_move', models.BooleanField(default=False, verbose_name='Primer Movimiento')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad de Producto',
                'verbose_name_plural': 'Unidades de Producto',
                'db_table': 'product_units',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('measure_qty', models.PositiveIntegerField(default=0.0, verbose_name='Factor de Cantidad')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
                ('measure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.measurement_units', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='products_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Piezas')),
                ('units_created', models.BooleanField(default=False)),
                ('unit_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Cantidad de Unidades')),
                ('fixed_ammount', models.BooleanField(default=False, verbose_name='Fijar Cantidad')),
                ('first_move', models.BooleanField(default=False, verbose_name='Primer Movimiento')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paquete de Productos',
                'verbose_name_plural': 'Paquetes de Productos',
                'db_table': 'products_package',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='stock_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('Null', 'Null'), ('Ingress', 'Ingress'), ('Egress', 'Egress'), ('Internal', 'Internal')], default='Null', max_length=8)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'stock_location',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='stock_move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('note', models.TextField(verbose_name='Notas')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('pieces', models.IntegerField(default=0.0, verbose_name='Piezas')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Cantidad')),
                ('prev_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Cantidad previa de la Unidad')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Saldo total de la Unidad')),
                ('prev_qty_origin', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Cantidad previa en el origen')),
                ('balance_origin', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Saldo nuevo en el origen')),
                ('prev_qty_dest', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Cantidad previa en el Destino')),
                ('balance_dest', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Saldo nuevo en el Destino')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('move_type', models.CharField(max_length=100, verbose_name='Tipo de Movimiento')),
                ('location_dest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.stock_location')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.stock_location')),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.products_package', verbose_name='Paquetes')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product_units', verbose_name='Unidad de Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'stock_move',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='stock_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Codigo')),
                ('pieces', models.IntegerField(default=0.0, verbose_name='Piezas')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Cantidad')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.stock_location')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product_units', verbose_name='Unidad de Producto')),
            ],
            options={
                'verbose_name': 'Control de Stock',
                'verbose_name_plural': 'Controles de Stock',
                'db_table': 'stock_control',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='products_package',
            name='location_from_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.stock_location', verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='products_package',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.stock_location', verbose_name='Hacia'),
        ),
        migrations.AddField(
            model_name='products_package',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.products', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='product_units',
            name='location_from_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.stock_location', verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='product_units',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.stock_location', verbose_name='Hacia'),
        ),
        migrations.AddField(
            model_name='product_units',
            name='package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.products_package', verbose_name='Paquete'),
        ),
        migrations.AddField(
            model_name='product_units',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.products', verbose_name='Producto'),
        ),
    ]
