# Generated by Django 2.2.12 on 2020-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_units',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='products_package',
            name='unit_qty',
            field=models.FloatField(default=0.0, verbose_name='Cantidad de Unidades'),
        ),
        migrations.AlterField(
            model_name='stock_control',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='stock_move',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Saldo total de la Unidad'),
        ),
        migrations.AlterField(
            model_name='stock_move',
            name='balance_dest',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Saldo nuevo en el Destino'),
        ),
        migrations.AlterField(
            model_name='stock_move',
            name='balance_origin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Saldo nuevo en el origen'),
        ),
        migrations.AlterField(
            model_name='stock_move',
            name='prev_qty',
            field=models.FloatField(default=0.0, verbose_name='Cantidad previa de la Unidad'),
        ),
        migrations.AlterField(
            model_name='stock_move',
            name='prev_qty_dest',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cantidad previa en el Destino'),
        ),
        migrations.AlterField(
            model_name='stock_move',
            name='prev_qty_origin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cantidad previa en el origen'),
        ),
        migrations.AlterField(
            model_name='stock_move',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Cantidad'),
        ),
    ]
